# Code of Conduct {#code}

## Please note that this is in draft, made available here for review

A _Code of Conduct_ is a set of basic ground rules that we ask participants in lab spaces to follow. The goal is to create an open and inclusive space for our work that helps us achieve our collective goals. Along with our lab culture/philosophy, it also provides a benchmark for self-evaluation and helps better define our identity as a community. 

While all members of the lab _**must**_ abide by the University of Cape Town's policies and guidelines (see multiple resources on the [Office for Inclusivity and Change website](http://www.oic.uct.ac.za/) and the [Science Faculty Code of Conduct](http://www.science.uct.ac.za/codes-conduct)), we'd like to go a step beyond to actively cultivate an open and inclusive space that celebrates all forms of diversity.

_We expect all lab members to adhere to the policies and guidelines outlined here._


## Lab policy

We're dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of participants in any form and prioritize marginalized people’s safety over privileged people’s comfort.

The University's policies and guidelines provide the framework governing the dos, don'ts and consequences for severe infringements. Our lab policy is aimed at reducing the occurrence of subtler forms of discrimination, often as the result of unconscious bias, hoping to actively improve ourselves, our lab and our society. For the most part we do this by having regular open courageous conversations about diversity, equity and inclusion in the lab and society, envisioning what we would like to have and what we need to do to get there. We're also experimenting with ways to create a safe space for calling out incidents of unconscious bias to help us all be more aware of and address our biases and their impacts on others. We include a "DEI Check-in" in our weekly lab meeting where lab members are invited to share ideas or resources or raise and discuss any issues they have experienced or are aware of in the lab, Department, University or society at large.


**Harassment includes (but is not limited to):**

* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.  
* Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
* Deliberate misgendering or use of ‘dead’ or rejected names.
* Deliberate “outing” of any aspect of a person’s identity without their consent except as necessary to protect vulnerable people from intentional abuse.
* Publication of non-harassing private communication.
* Gratuitous or off-topic sexual images or behaviour in spaces where they’re not appropriate.
* Physical contact and simulated physical contact (eg, textual descriptions like “*hug*” or “*backrub*”) without consent or after a request to stop.
* Unwelcome sexual attention.
* Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others
* Stalking or following.
* Continued one-on-one communication after requests to cease.
* Harassing photography or recording, including logging online activity for harassment purposes.
* Sustained disruption of discussion.
* Threats of violence.
* Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
* Deliberate intimidation.


### Reporting

If you are being harassed by a member of the Plant Ecology Lab, notice that someone else is being harassed, or have any other concerns (including outside the lab and even if you're not sure it counts as harassment), please contact the PI, Dr Jasper Slingsby. 

If you do not wish to contact Dr Slingsby, here are other options:

The are various contacts through the [Office for Inclusivity and Change website](http://www.oic.uct.ac.za/), including (but not limited to):

* Online Reporting for Gender Based Violence, Racism, Disability and related discrimination and harassment: [https://casereporting.uct.ac.za/ReportingPage/](https://casereporting.uct.ac.za/ReportingPage/)
* Sexual Assault Emergency Standby Number 072 393 7824 / 021 650 3530

Lab members who believe they have been subjected to any kind of discrimination that conflicts with the University's policies and/or the laws of the country should seek assistance from the [Office for Inclusivity and Change](http://www.oic.uct.ac.za/).


## License and attribution

This anti-harassment policy is based on the [example policy created by the Geek Feminism community](https://geekfeminism.wikia.org/wiki/Community_anti-harassment).
